### ISSUE TITLE
Mastercard Debit Cards coming back as Visa Debit Cards

### ISSUE THREAD

**Issue by ChromeOrange** [binlist/data#102]
As per the title

![](https://pbs.twimg.com/media/ChHe4TgWUAQlIJs.jpg)

![](https://pbs.twimg.com/media/ChHe4TwXEAAMGHo.jpg)

**Comment by ChromeOrange** [comment]
I'm finding others now

eg

356999 should be JCB, BinList says MasterCard Debit (https://binlists.com/356999)
374200 should be Amex, BinList says Visa Delta (https://binlists.com/374200)

**Comment by tjconcept** [comment]
Hi Andrew,

Thanks for your issue, this should now be fixed.

We've recently concluded a larger overhaul of the project and the API is out in a new version. Please see https://binlist.net for how to use it. To get important API updates, sign up to this mailing list: http://eepurl.com/cNddUP
