### ISSUE TITLE
Get `bank_phone`

### ISSUE THREAD

**Issue by int99h** [binlist/data#103]
There is a `bank_phone` at `ranges.csv`... can U add this field to API responses?
Is it legal?

thanks in advance

**Comment by elvarb** [comment]
Might be hard to keep accurate in the long run, but would be a nice addition.

**Comment by tjconcept** [comment]
Hi Stanislav,

Thanks for your issue.

We've recently concluded a larger overhaul of the project and the API is out in a new version. This includes the "phone" field. However be aware that not all responses will have this.

Please see https://binlist.net for how to use it. To get important API updates, sign up to this mailing list: http://eepurl.com/cNddUP
