### ISSUE TITLE
UK AMEX displaying as US Visa Debit

### ISSUE THREAD

**Issue by jasonedwards1** [binlist/data#105]
Hiya,

One reoccurant problem we have with the information provided by yourselves is that all UK issued Amex cards you state are Visa Debit Cards issued in the US and results in under collecting on card charges.  All other bin checkers pick this up correctly? Any chance you can fix that?

**Comment by tjconcept** [comment]
Hi Jason,

Thanks for your issue. I believe this is now fixed.

We've recently concluded a larger overhaul of the project and the API is out in a new version. Please see https://binlist.net for how to use it. To get important API updates, sign up to this mailing list: http://eepurl.com/cNddUP
