### ISSUE TITLE
the license of the data

### ISSUE THREAD

**Issue by taakazazzz** [binlist/data#112]
What's the license of the data? Can I use it in my commercial project?

**Comment by jonasbjork** [comment]
It seems to be released under Apache License 2.0

License in full: http://www.apache.org/licenses/LICENSE-2.0

**Comment by tjconcept** [comment]
Hi both,

The service itself is considered production ready and usable for commercial projects.

Regarding the user data in here, it's not covered by a license. It is not really useful in looking up BINs as it covers 2-5 % of the ranges (read my comments at: https://github.com/binlist/data/issues/139#issuecomment-283496543).
