### ISSUE TITLE
Add reporting mechanism directly to the website

### ISSUE THREAD

**Issue by aes** [binlist/data#120]
By adding a new info / error reporting form directly on the website, you could both cut down on the nonsense detail issues reported and get a much more fine-grained confidence and quality control.

**Comment by tjconcept** [comment]
Hi Anders,

Thanks for your issue.

I assume you are referring to some kind of feedback option on the website in regards to the credit card information returned. This is something we are looking into adding in the future.

We've recently concluded a larger overhaul of the project and the API is out in a new version. Please see https://binlist.net for how to use it. To get important API updates, sign up to this mailing list: http://eepurl.com/cNddUP
