### ISSUE TITLE
What do I suppose to do with binlist mistakes?

### ISSUE THREAD

**Issue by lobkovich** [binlist/data#124]
My Mastercard Credit Card from UK 522948 reading as Visa Debit Card from US.
I can see that it is common issue for that web site.
Does anyone knows How it can be corrected? Or whom  can I write to get result?

**Comment by rcchan** [comment]
You could send in an update by opening a [pull request](https://github.com/binlist/data/pulls)
Otherwise, file an issue with the correct information and someone can try to fix it.

**Comment by avimar** [comment]
... there's lots of pulls waiting. And some bogus issues still open. 

Last commit was 10months ago.

Anybody around..?

**Comment by zahmaci** [comment]
This project really good but as @avimar mentioned nobody updating the database.
So lets create a new database using binlist's current data ? Anybody wants it ?

**Comment by avimar** [comment]
I got much more data from e.g. https://binlists.com/ ... not sure where they get their data, but seemed much better.

**Comment by zahmaci** [comment]
@avimar if you have their data could you also share with us ?

**Comment by avimar** [comment]
No, I don't have all their data.

I just needed one country (special regulations) so I was able to see the list for one country.

**Comment by greendevilapps** [comment]
I have an updated list [here](https://github.com/greendevilapps/iinlist), but it still needs some more work.

**Comment by tjconcept** [comment]
Hi all,

The UK Mastercard in question should now read correctly in the service.

Regarding the user data in this repo, please read my previous comments at: https://github.com/binlist/data/issues/139#issuecomment-283496543

We've recently concluded a larger overhaul of the project and the API is out in a new version. Please see https://binlist.net for how to use it. To get important API updates, sign up to this mailing list: http://eepurl.com/cNddUP
