### ISSUE TITLE
Apple Pay BIN

### ISSUE THREAD

**Issue by hoverlover** [binlist/data#133]
Hi, at least one US Amex BIN is reporting incorrectly as a Visa Debit.  I know apple pay uses a DAN (Device Account Number) instead of the real PAN.  Does this project support Apple Pay DANs?

**Comment by hoverlover** [comment]
Actually looking at `ranges.csv` it appears that file has it listed it [correctly](https://github.com/binlist/data/blob/master/ranges.csv#L8).  The Amex BIN in question is `370295`.  Has binlist.net just need updating?

**Comment by tjconcept** [comment]
Hi Chad,

Apple Pay DANs might be supported in the Visa and Mastercard ranges.

The AMEX BIN should show correctly now.

We've recently concluded a larger overhaul of the project and the API is out in a new version. Please see https://binlist.net for how to use it. To get important API updates, sign up to this mailing list: http://eepurl.com/cNddUP
