### ISSUE TITLE
Incorrect result for 360886

### ISSUE THREAD

**Issue by ds1payuin** [binlist/data#143]
This is a DINERS Credit Card (INDIA) but results say VISA Debit Card (USA).

**Comment by tjconcept** [comment]
Hi @ds1payuin 

Thanks for the issue.

Could you please take a photo of both the front and back of the card, mask the card number from the seventh digit, the cvc, the expiry, and any other personal data, and send it for me at thomas@paylike.io?

**Comment by kladskull** [comment]
May 9? Abandoned project? I get the same... in July....

curl https://lookup.binlist.net/370754
{"scheme":"VISA","number":{"length":19,"prefix":"370754"},"type":"DEBIT","brand":"Visa Plus","prepaid":false,"bank":{},"country":{"alpha2":"US","name":"United States","numeric":"840","latitude":38,"longitude":-97}}

**Comment by kladskull** [comment]
why is that happening ?

**Comment by tjconcept** [comment]
Might be the same as #154, otherwise please submit as many answers for the following form to binlist@src.agency: https://gist.github.com/tjconcept/a839e6715a7e71c11c0f508c0cc6323b to correct or add new IINs.
