### ISSUE TITLE
BIN working via API but not in CSV

### ISSUE THREAD

**Issue by hobailey** [binlist/data#45]
Hello, 
Is there a particular reason why some BINs are correctly returned via the API, but are not found in the CSV? For example: 581750.
Thanks for any help.

**Comment by binlistnet** [comment]
@hobailey please add a few sample outputs for us to reproduce.

**Comment by hobailey** [comment]
Hi @binlistnet, thanks for the response, although I'm not sure how to make it clearer I'm afraid.
http://www.binlist.net/json/581750 returns an output of 
 ``{"bin":"581750","brand":"MAESTRO","sub_brand":"","country_code":"FR","country_name":"France","bank":"","card_type":"DEBIT","card_category":"","latitude":"46","longitude":"2","query_time":"238.52Âµs"}``
whereas searching for the same bin (581750) in the csv (https://raw.githubusercontent.com/binlist/binlist-data/master/iin-user-contributions.csv) returns nothing

**Comment by cip91sk** [comment]
I have the same issue with 533317, it gives me a correct answer via API, but I can't find the entry in the csv

**Comment by asturur** [comment]
@cip91sk Where did you find this non free csv?

**Comment by cip91sk** [comment]
@asturur I just find mentions of it, it should be a "private" list that only binlist.net has access to.

**Comment by alexvodovoz** [comment]
@binlistnet is there anyway to get the bin list that the api uses?  Another example of a bin number that exists through the api but is not part of the list available in github is 424242

**Comment by asturur** [comment]
@alexvodovoz no there is a closed issue about that. api data cannot be published with offline file

**Comment by tjconcept** [comment]
This repository contains just the user contributions.
