### ISSUE TITLE
the correct BIN for 532017, which is a Spanish BIN 

### ISSUE THREAD

**Issue by SaraSPI** [binlist/data#53]
https://github.com/SparkCardAdding the correct BIN for 532017, which is a Spanish BIN and not a US BIN. The BIN is owned by SPARK SPAIN which offers prepaid cards. Thanks

 Is posible to change it?

sara

**Comment by tjconcept** [comment]
Hi,

Thanks for your issue, this should now be fixed.

We've recently concluded a larger overhaul of the project and the API is out in a new version. Please see https://binlist.net for how to use it. To get important API updates, sign up to this mailing list: http://eepurl.com/cNddUP
