### ISSUE TITLE
Card category options

### ISSUE THREAD

**Issue by rcchan** [binlist/data#55]
Seems like the category column corresponds roughly to LEVEL in bindb.com

We only allow: CLASSIC|STANDARD|PRESTIGE|PLATINUM
Whereas the documentation there (and the results of some binlist.net lookups) contains: PREPAID|GOLD|GIFT|BUSINESS|ELECTRON|WORLD ELITE

Should the schema restrictions be expanded?

**Comment by tjconcept** [comment]
We are in the process of adding more data, such as this, but we need to dig a little deeper to find a structure that won't bite us in the long run. Stay tuned.
