### ISSUE TITLE
Server Down!!

### ISSUE THREAD

**Issue by pocketdeveloper** [binlist/data#72]
Hey there, the server has been down for more than 13 hours. Are you working on a solution? We really depend on this amazing work you've done! 

Please!!!!!!!

**Comment by tjconcept** [comment]
Thanks for this issue, which I suppose is no longer relevant.

We've recently concluded a larger overhaul of the project and the API is out in a new version. Please see https://binlist.net for how to use it. To get important API updates, sign up to this mailing list: http://eepurl.com/cNddUP
