### ISSUE TITLE
bilist.net site is down with REDIRECT errors (15/JAn/16) 

### ISSUE THREAD

**Issue by jalsco** [binlist/data#80]
The page isn't redirecting properly  <- firefox

This web page has a redirect loop  <-- chrome
ERR_TOO_MANY_REDIRECTS

**Comment by tjconcept** [comment]
This should now be fixed. Thanks for your patience.

We've recently concluded a larger overhaul of the project and the API is out in a new version. Please see https://binlist.net for how to use it. To get important API updates, sign up to this mailing list: http://eepurl.com/cNddUP
