### ISSUE TITLE
JSONP endpoint

### ISSUE THREAD

**Issue by SamPotts** [binlist/data#87]
Hey,

This used to work but now it just returns JSON:
https://www.binlist.net/json/411111?callback=test

Can we get JSONP back please?

Cheers

**Comment by tjconcept** [comment]
Sure, give me ten!

On another note; why not use CORS?

**Comment by SamPotts** [comment]
Awesome, cheers.

Yeah CORS would work also but it looks like the "Access-Control-Allow-Origin" header isn't set to "*" and I get:
```
XMLHttpRequest cannot load https://www.binlist.net/json/465941. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin is therefore not allowed access.
```

**Comment by tjconcept** [comment]
CORS should we enabled now. Give it a spin!

**Comment by SamPotts** [comment]
Awesome! Works perfectly. Cheers for that.

**Comment by tjconcept** [comment]
JSONP support is added now: https://www.binlist.net/json/431940?callback=test or more explicitly https://www.binlist.net/jsonp/431940?callback=test

**Comment by SamPotts** [comment]
Cool. Top work :+1:
