### ISSUE TITLE
557379 was correct, but is now incorrect.

### ISSUE THREAD

**Issue by sgmoore** [binlist/data#88]
Last month (and possibly even last week) 557379 was correctly showing as MasterCard Debit from United Kingdom.

Now it is showing as a Visa Debit card from the US.

**Comment by MikeDeRoiste** [comment]
Same issue exists for, 544156. It is a Mastercard Debit from United Kingdom but shows up as Visa Debit from US.

**Comment by tjconcept** [comment]
I am currently investigating this. It seems like we have a collision with a Visa range. The nature of the problem is a bit more complex as Visa and MasterCard can coexist on ranges as long as they differ in the total length of the card number.

**Comment by tjconcept** [comment]
This should now be fixed. Thanks for your patience.

We've recently concluded a larger overhaul of the project and the API is out in a new version. Please see https://binlist.net for how to use it. To get important API updates, sign up to this mailing list: http://eepurl.com/cNddUP
