### ISSUE TITLE
correct brand of BIN 374202

### ISSUE THREAD

**Issue by christitan** [binlist/data#90]
Präfix 37 is always AMEX, not visa

**Comment by tjconcept** [comment]
Can I verify this independently somewhere? There are ranges from official Visa data in that prefix.

**Comment by tjconcept** [comment]
I've been looking closer to this, and although there are Visa ranges within `37`, they are not for ecommerce use. Thus I've filtered them from the service and you should now see more AMEX ranges like you expect.

We've recently concluded a larger overhaul of the project and the API is out in a new version. Please see https://binlist.net for how to use it. To get important API updates, sign up to this mailing list: http://eepurl.com/cNddUP
