### ISSUE TITLE
Missing Bin 379763

### ISSUE THREAD

**Issue by kmcduffie** [binlist/data#91]
Hi,

I know in the past this bin mapped to AMEX. However, currently the service returns VISA. I physically have a card that shows AMEX. I looked at your BIN data and it looks like you have the prefix 3797 mapping to AMEX for 4 combinations of 2 numbers after that. Is there a chance that the big revamp dropped this bin?

**Comment by tjconcept** [comment]
Hi Kelly,

Thanks for your issue, this should now be fixed.

We've recently concluded a larger overhaul of the project and the API is out in a new version. Please see https://binlist.net for how to use it. To get important API updates, sign up to this mailing list: http://eepurl.com/cNddUP
