### ISSUE TITLE
bin 525615 error

### ISSUE THREAD

**Issue by dekser** [binlist/data#94]
bin 525615 is  a DE MASTERCARD  CREDIT  STANDARD    VERBAND DER SPARDA BANKEN E.V., not US visa like stated

**Comment by dekser** [comment]
also 403650 is missing, VISA	CREDIT	PREMIER	DEUTSCHER SPARKASSEN- UND GIROVERBAND

**Comment by dekser** [comment]
also 	525615

**Comment by tjconcept** [comment]
Hi,

Thanks for your issue, this should now be fixed.

We've recently concluded a larger overhaul of the project and the API is out in a new version. Please see https://binlist.net for how to use it. To get important API updates, sign up to this mailing list: http://eepurl.com/cNddUP
