### ISSUE TITLE
530826 bin is incorrect

### ISSUE THREAD

**Issue by COTOHA** [binlist/data#96]
it's shown as USA, while it is Switzerland 
https://binlists.com/530826

**Comment by tjconcept** [comment]
Hi,

Thanks for your issue, this should now be fixed.

We've recently concluded a larger overhaul of the project and the API is out in a new version. Please see https://binlist.net for how to use it. To get important API updates, sign up to this mailing list: http://eepurl.com/cNddUP

It seems like you are linking to another project though, be sure to enter "530826" into our service at https://binlist.net
